### ISSUE TITLE
Reconnect on status unavailable in Home Assistant [Feature Request]

### ISSUE THREAD

**Issue by pravardhanreddy** [milothomas/ha-miraie-ac#12]
I don't know if it's a problem with my AC or something else, but from time to time, the status of the AC becomes unavailable in Home Assistant. All I need to do to fix it is move the Node in Node-RED and hit deploy, and the AC is back up on HA.

So whatever is happening on hitting deploy (maybe reconnect to the HA and Mirai brokers??) is it possible to do it automatically whenever the status becomes unavailable?

**Comment by milothomas** [comment]
Yes, I have noticed this as well and just fixed it (from my tests).

**Comment by milothomas** [comment]
I see that this still occurs periodically - reopening.

**Comment by harshithmohan** [comment]
Just got a new AC. Happening with me too

**Comment by milothomas** [comment]
Hey @pravardhanreddy and @harshithmohan, thanks for the feedback. I believe this has been fixed in the latest version 2.0.0.

**Comment by smamudhan** [comment]
Sadly no, I just set this up a week back; and it's still happening, like @pravardhanreddy says, moving the node and redeploying fixes it; then it happens again.

**Comment by maxakash** [comment]
@smamudhan @milothomas @harshithmohan did you find a solution to this?
